In [1]:
#1D matrix 
import torch

x = torch.empty(1)
print(x)

tensor([6.4888e+35])


In [2]:
#1D matrix
import torch

x = torch.empty(3)
print(x)

tensor([9.0106e+35, 4.5860e-41, 9.0109e+35])


In [3]:
#2d matrix
import torch

x = torch.empty(2,3)
print(x)

tensor([[ 1.1549e-32,  4.5862e-41, -7.2918e+34],
        [ 3.0627e-41,  4.4842e-44,  0.0000e+00]])


In [8]:
#3d matrix
import torch

x = torch.empty(2,2,3)
print(x)

tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  1.4013e-45,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00, -4.6575e+18],
         [ 4.5860e-41,  0.0000e+00,  0.0000e+00]]])


In [13]:
# with random no
#2d matrix
import torch

x = torch.rand(2,3)
print(x)

tensor([[0.7662, 0.6361, 0.9211],
        [0.2719, 0.3029, 0.9445]])


In [14]:
# with numpy 
#2d matrix
import torch

x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [15]:
# with numpy 
#2d matrix
import torch

x = torch.ones(2,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [16]:
# checking type
# with numpy 
#2d matrix
import torch

x = torch.zeros(2,3)
print(x.dtype)

torch.float32


In [22]:
# changing type  and check size
# with numpy 
#2d matrix
import torch

x = torch.zeros(2,3, dtype=torch.int)  #can use float16, double, float
print(x.dtype)
print(x.size())    # shows the size

torch.int32
torch.Size([2, 3])


In [24]:
# Creating tensor

import torch

x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [25]:
# Creating tensor and doing operations

import torch

x = torch.rand(2,2)
y = torch.rand(2,2)

print(x)
print(y)

z = x + y
print(z)

tensor([[0.2329, 0.4005],
        [0.7432, 0.1725]])
tensor([[0.0652, 0.6893],
        [0.8986, 0.3419]])
tensor([[0.2981, 1.0899],
        [1.6418, 0.5144]])


In [26]:
# Another method

import torch

x = torch.rand(2,2)
y = torch.rand(2,2)

z = torch.add(x,y)
print(z)


tensor([[1.0533, 0.9156],
        [1.5649, 0.6652]])


In [27]:
# Another way

import torch

x = torch.rand(2,2)
y = torch.rand(2,2)

y.add_(x)     # inplace operation
print(y)

tensor([[0.8876, 1.0765],
        [0.4492, 1.2349]])


In [31]:
#other Operations (sub,mul.div)

import torch

x = torch.rand(2,2)
y = torch.rand(2,2)

#sub
z = x - y
print(z)

y.sub_(x)
print(y)


#mul
z = x * y
print(z)

y.mul_(x)
print(y)

#div
z = y / x
print(z)

y.div_(x)
print(y)

tensor([[ 0.9043,  0.3655],
        [-0.7311, -0.0386]])
tensor([[-0.9043, -0.3655],
        [ 0.7311,  0.0386]])
tensor([[-0.8492, -0.2134],
        [ 0.1821,  0.0230]])
tensor([[-0.8492, -0.2134],
        [ 0.1821,  0.0230]])
tensor([[-0.9043, -0.3655],
        [ 0.7311,  0.0386]])
tensor([[-0.9043, -0.3655],
        [ 0.7311,  0.0386]])


In [35]:
#Slicing

x = torch.rand(5,3)
print(x)

print(x[:,0]) #print column
print(x[1,:])  #print row

tensor([[0.2270, 0.8203, 0.5905],
        [0.0214, 0.4023, 0.8639],
        [0.1298, 0.3354, 0.2525],
        [0.4930, 0.8128, 0.2093],
        [0.6890, 0.6251, 0.3735]])
tensor([0.2270, 0.0214, 0.1298, 0.4930, 0.6890])
tensor([0.0214, 0.4023, 0.8639])


In [37]:
# getting tensor only one value
x = torch.rand(5,3)
print(x)

print(x[1,1])  #getting tensor with one value

print(x[1,1].item())   # getting actual value

tensor([[0.6862, 0.9064, 0.4861],
        [0.2625, 0.7599, 0.2606],
        [0.5210, 0.3180, 0.7173],
        [0.0678, 0.8320, 0.2099],
        [0.9097, 0.1881, 0.1426]])
tensor(0.7599)
0.7599034309387207


In [42]:
# reshaping tensor

x = torch.rand(4,4)
print(x)

y = x.view(16)
print(y)   # resize tensor


tensor([[0.7365, 0.4204, 0.0035, 0.3997],
        [0.6714, 0.5961, 0.8411, 0.6150],
        [0.5434, 0.7662, 0.9086, 0.5754],
        [0.9267, 0.4613, 0.0159, 0.7295]])
tensor([0.7365, 0.4204, 0.0035, 0.3997, 0.6714, 0.5961, 0.8411, 0.6150, 0.5434,
        0.7662, 0.9086, 0.5754, 0.9267, 0.4613, 0.0159, 0.7295])


In [44]:
# Another way

x = torch.rand(4,4)
print(x)

y = x.view(-1,8)   # -1 helps automatically resize the tensor
print(y)
print(y.size())   


tensor([[0.3744, 0.6760, 0.0576, 0.0827],
        [0.9024, 0.5547, 0.8823, 0.8625],
        [0.1255, 0.2807, 0.4992, 0.1620],
        [0.9857, 0.0465, 0.5653, 0.2292]])
tensor([[0.3744, 0.6760, 0.0576, 0.0827, 0.9024, 0.5547, 0.8823, 0.8625],
        [0.1255, 0.2807, 0.4992, 0.1620, 0.9857, 0.0465, 0.5653, 0.2292]])
torch.Size([2, 8])


In [49]:
# creating tensor to numpy array

import torch
import numpy as np

a = torch.ones(5)
print(a)

b = a.numpy()
print(b,(type(b)))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [50]:
import torch
import numpy as np

a = torch.ones(5)
print(a)

b = a.numpy()
print(b,(type(b)))

a.add_(1)   # be carefull it store in same memory location
print(a)

print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [53]:
import torch
import numpy as np

a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

a += 1            # be carefull it store in same memory location
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
