# Autograd

In [6]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y*y*2
print(z)

z = z.mean()
print(z)

z.backward()  #dz/dx   backpropogation
print(x.grad)

tensor([-0.5411, -1.7938,  1.4501], requires_grad=True)
tensor([1.4589, 0.2062, 3.4501], grad_fn=<AddBackward0>)
tensor([ 4.2568,  0.0851, 23.8070], grad_fn=<MulBackward0>)
tensor(9.3830, grad_fn=<MeanBackward0>)
tensor([1.9452, 0.2750, 4.6002])


In [8]:
import torch

x = torch.randn(3, requires_grad=False)  # it give error
print(x)

y = x + 2
print(y)

z = y*y*2
print(z)

#z = z.mean()   # mean gives scaler output
#print(z)

z.backward()  #dz/dx   backpropogation
print(x.grad)

tensor([ 1.2773,  0.2092, -1.5675])
tensor([3.2773, 2.2092, 0.4325])
tensor([21.4812,  9.7614,  0.3742])


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [10]:
import torch

x = torch.randn(3, requires_grad=True)  # it give error
print(x)

y = x + 2
print(y)

z = y*y*2
print(z)

#z = z.mean()   # mean gives scaler output
#print(z)

#we need vector to call it not scaler
v = torch.tensor([0.1,1.0,0.001])
z.backward(v)  #dz/dx   backpropogation
print(x.grad)

tensor([-0.6274,  0.4092,  1.5445], requires_grad=True)
tensor([1.3726, 2.4092, 3.5445], grad_fn=<AddBackward0>)
tensor([ 3.7683, 11.6085, 25.1269], grad_fn=<MulBackward0>)
tensor([0.5491, 9.6368, 0.0142])


In [14]:
# stopping pytorch from creating gradient functions with these 3 methods

import torch

x = torch.randn(3, requires_grad=True) 
print(x)

#x.reqires_grad(False)

x.requires_grad_(False)
print(x)

tensor([-0.3984, -0.3274,  1.1184], requires_grad=True)
tensor([-0.3984, -0.3274,  1.1184])


In [15]:
import torch

x = torch.randn(3, requires_grad=True) 
print(x)

#y.detach()

y = x.detach()
print(y)


tensor([ 0.5139, -0.3088,  0.7290], requires_grad=True)
tensor([ 0.5139, -0.3088,  0.7290])


In [17]:
import torch

x = torch.randn(3, requires_grad=True) 
print(x)

#with torch.no_grad()

with torch.no_grad():
    y = x + 2
    print(y)


tensor([-1.0992,  0.9091,  0.4557], requires_grad=True)
tensor([0.9008, 2.9091, 2.4557])


In [21]:
# Dummy training example
import torch

weights = torch.ones(4, requires_grad=True)

for epoch in range(3):       # change ephoch range to 2,3,4,5
    model_output = (weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [22]:
# Dummy training example
import torch

weights = torch.ones(4, requires_grad=True)

for epoch in range(3):       # change ephoch range to 2,3,4,5
    model_output = (weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
