# Tensors

In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
 # printing array and later converted array to tensors
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(f"Numpy np_array value: \n {np_array} \n")
print(f"Tensor x_np value: \n {x_np} \n")

# multiplying array by 2 and then converting to tensors and then printing it 
np.multiply(np_array, 2, out=np_array)

print(f"Numpy np_array after * 2 operation: \n {np_array} \n")
print(f"Tensor x_np value after modifying numpy array: \n {x_np} \n")

Numpy np_array value: 
 [[1 2]
 [3 4]] 

Tensor x_np value: 
 tensor([[1, 2],
        [3, 4]]) 

Numpy np_array after * 2 operation: 
 [[2 4]
 [6 8]] 

Tensor x_np value after modifying numpy array: 
 tensor([[2, 4],
        [6, 8]]) 



In [5]:
# convert x_data ito ones_like array printing it as tensors
# then that tensors modify by using random_like method as as float values and printing it as tensors

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4541, 0.2029],
        [0.1696, 0.8855]]) 



## shape is a tuple of tensor dimensions.

In [6]:
# Genrating tensors with different methods

shape = (2,3)        # 2 rows 3 columns

rand_tensor = torch.rand(shape)   # genrating random numbers tensor

ones_tensor = torch.ones(shape)   # genrating one's number as tensors

zeros_tensor = torch.zeros(shape)  # genrating zeros numbers as tensors

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7910, 0.0187, 0.1019],
        [0.6461, 0.3700, 0.6691]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [8]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

# Standard numpy-like indexing and slicing:

In [9]:
# Genrating 4 by 4 tensor of one's

tensor = torch.ones(4, 4)

print('First row: ',tensor[0])    # printing first row
print('First column: ', tensor[:, 0])    # printing first column
print('Last column:', tensor[..., -1])    # printing last column
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [10]:
# Genrating random number 4 by 4 tensor

Random_no_tensor = torch.rand(4, 4)

print('First row: ',Random_no_tensor[0])    # printing first row
print('First column: ', Random_no_tensor[:, 0])    # printing first column
print('Last column:', Random_no_tensor[..., -1])    # printing last column
Random_no_tensor[:,1] = 0
print(Random_no_tensor)

First row:  tensor([0.6551, 0.1992, 0.8455, 0.7015])
First column:  tensor([0.6551, 0.4089, 0.2315, 0.1236])
Last column: tensor([0.7015, 0.0998, 0.8950, 0.0773])
tensor([[0.6551, 0.0000, 0.8455, 0.7015],
        [0.4089, 0.0000, 0.0197, 0.0998],
        [0.2315, 0.0000, 0.3812, 0.8950],
        [0.1236, 0.0000, 0.2226, 0.0773]])


# Joining tensors

In [11]:
t1 = torch.cat([Random_no_tensor, tensor], dim=1)
print(t1)

tensor([[0.6551, 0.0000, 0.8455, 0.7015, 1.0000, 0.0000, 1.0000, 1.0000],
        [0.4089, 0.0000, 0.0197, 0.0998, 1.0000, 0.0000, 1.0000, 1.0000],
        [0.2315, 0.0000, 0.3812, 0.8950, 1.0000, 0.0000, 1.0000, 1.0000],
        [0.1236, 0.0000, 0.2226, 0.0773, 1.0000, 0.0000, 1.0000, 1.0000]])


# Arithmetic operations

In [12]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [13]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [14]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = Random_no_tensor @ Random_no_tensor.T
y2 = Random_no_tensor.matmul(Random_no_tensor.T)

y3 = torch.rand_like(Random_no_tensor)
torch.matmul(Random_no_tensor, Random_no_tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = Random_no_tensor * Random_no_tensor
z2 = Random_no_tensor.mul(Random_no_tensor)

z3 = torch.rand_like(Random_no_tensor)
torch.mul(Random_no_tensor, Random_no_tensor, out=z3)

tensor([[4.2913e-01, 0.0000e+00, 7.1484e-01, 4.9217e-01],
        [1.6719e-01, 0.0000e+00, 3.8862e-04, 9.9559e-03],
        [5.3613e-02, 0.0000e+00, 1.4532e-01, 8.0099e-01],
        [1.5282e-02, 0.0000e+00, 4.9557e-02, 5.9812e-03]])

# Single-element tensors
### If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():

In [15]:
agg = tensor.sum()
agg_item = agg.item()  
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [16]:
# For random numbers
agg = Random_no_tensor.sum()
agg_item = agg.item()  
print(agg_item, type(agg_item))

4.66180419921875 <class 'float'>


# In-place operations
### Operations that store the result into the operand are called in-place. 
### They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

In [17]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# Bridge with NumPy
### Tensors on the CPU and NumPy arrays can share their underlying memory locations,
### and changing one will change the other.
## Tensor to NumPy array

In [18]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


### A change in the tensor reflects in the NumPy array.

In [19]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy array to Tensor

In [20]:
n = np.ones(5)
t = torch.from_numpy(n)

### Changes in the NumPy array reflects in the tensor.



In [21]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
