# Softmax

In [3]:
import torch
import torch.nn as nn
import numpy as np

def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

x = np.array([2.0,1.0,0.1])    #higher values have higher probabilities
outputs = softmax(x)
print('softmax numpy : ',outputs)

#tensor method
x = torch.tensor([2.0,1.0,0.1])      # result is almost same
outputs = torch.softmax(x, dim=0)
print(outputs)

softmax numpy :  [0.65900114 0.24243297 0.09856589]
tensor([0.6590, 0.2424, 0.0986])


# Cross-Entropy

In [6]:
import torch 
import torch.nn as nn
import numpy as np

def CrossEntropy(actual , predicted):
    loss = -np.sum(actual * np.log(predicted))
    return loss   #float(predicted.shape[0])

# y must be one hot encoded
# if class0 :[1,0,0]
#if class1 : [0,1,0]
#if class2 : [0,0,1]

Y = np.array([1,0,0])

# y pred has probabilities
Y_pred_good = np.array([0.7,0.2,0.1])
Y_pred_bad = np.array([0.1,0.3,0.6])

l1 = CrossEntropy(Y, Y_pred_good)
l2 = CrossEntropy(Y, Y_pred_bad)
print(f'loss1 numpy: {l1:.4f}')
print(f'loss2 numpy: {l2:.4f}')
    

loss1 numpy: 0.3567
loss2 numpy: 2.3026


# Cross-Entropy with Torch

In [12]:
import torch 
import torch.nn as nn
import numpy as np

loss = nn.CrossEntropyLoss()

Y = torch.tensor([0])

#nsamples * nclass = 1 * 3

Y_pred_good = torch.tensor([[2.0,1.0,0.1]])
Y_pred_bad = torch.tensor([[0.5,2.0,0.3]])

l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)

print(l1.item())   # lower cross entropy loss
print(l2.item())   # higher cross entropy loss

_, predictions1 = torch.max(Y_pred_good, 1)
_, predictions2 = torch.max(Y_pred_bad, 1) 

print(predictions1)
print(predictions2)

0.4170299470424652
1.840616226196289
tensor([0])
tensor([1])


In [14]:
# Increasing classes or sample

import torch 
import torch.nn as nn
import numpy as np

loss = nn.CrossEntropyLoss()

Y = torch.tensor([2,0,1])

#nsamples * nclass = 3 * 3

Y_pred_good = torch.tensor([[2.0,1.0,0.1],[3.0,1.0,0.1],[2.0,4.0,0.1]])
Y_pred_bad = torch.tensor([[0.5,2.0,0.3],[0.5,1.0,0.3],[0.5,1.0,4.3]])

l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)

print(l1.item())   # lower cross entropy loss
print(l2.item())   # higher cross entropy loss

_, predictions1 = torch.max(Y_pred_good, 1)
_, predictions2 = torch.max(Y_pred_bad, 1) 

print(predictions1)
print(predictions2)

0.8786281943321228
2.2138671875
tensor([0, 0, 1])
tensor([1, 1, 2])
